{{- range $name, $_ := $.Values.gcp.frontendConfigs }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
  {{- with .sslPolicy }}
  sslPolicy: {{ . }}
  {{- end }}
  {{- with .redirectToHttps }}
  redirectToHttps:
    enabled: {{ .enabled }}
    responseCodeName: {{ .responseCodeName | default "MOVED_PERMANENTLY_DEFAULT" }}
  {{- end }}
{{- end }}
