{{- range $name, $_ := $.Values.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
  {{- with .storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  {{- with .volumeMode }}
  volumeMode: {{ . }}
  {{- end }}
  accessModes:
  {{- toYaml .accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
