{{- range $name, $_ := $.Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
type: {{ .type | default "Opaque" }}
{{- if kindIs "bool" (get . "immutable") }}
immutable: {{ .immutable }}
{{- end }}
{{- with .data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .stringData }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
