{{- range $name, $_ := $.Values.rbac.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- include "helpers.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
{{- if kindIs "bool" .automountServiceAccountToken }}
automountServiceAccountToken: {{ .automountServiceAccountToken }}
{{- end }}
{{- end }}
