{{- range $name, $_ := $.Values.clusterExternalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
  externalSecretName: {{ .externalSecretName | default (printf "%s-%s" (include "helpers.app.name" $) $name) }}
  namespaceSelector:
    {{- include "helpers.render" (dict "value" .namespaceSelector "context" $) | nindent 4 }}
  externalSecretSpec:
    {{- include "helpers.external-secrets.externalSecret" (dict "component" $name "value" .externalSecretSpec "context" $) | nindent 4 }}
  {{- with .refreshTime }}
  refreshTime: {{ . }}
  {{- end }}
  {{- with .externalSecretMetadata }}
  externalSecretMetadata:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
