{{- range $name, $_ := $.Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
  {{- include "helpers.external-secrets.externalSecret" (dict "component" $name "value" . "context" $) | nindent 2 }}
{{- end }}
