{{- range $name, $_ := $.Values.secretStores }}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "helpers.app.name" $ }}-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helpers.app.labels" $ | nindent 4 }}
spec:
  provider:
    {{- toYaml .provider | nindent 4 }}
  {{- with .controller }}
  controller: {{ . }}
  {{- end }}
  {{- with .refreshInterval }}
  refreshInterval: {{ . }}
  {{- end }}
  {{- with .retrySettings }}
  retrySettings:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
