image:
  repository: traefik/whoami
  tag: v1.8.7

deployments:
  web:
    containers:
      web:
        envFromSecret:
          postgresql:
            DB_PASSWORD: password

externalSecrets:
  postgresql:
    refreshInterval: "0"
    secretStoreRef:
      name: vault
    data:
    - secretKey: password
      remoteRef:
        key: /postgresql/whoami/password
  registry:
    secretStoreRef:
      kind: ClusterSecretStore
      name: gcpsm
    dataFrom:
    - extract:
        key: /gitlab/registry

secretStores:
  vault:
    refreshInterval: 8h
    provider:
      fake:
        data:
        - key: /postgresql/whoami/password
          value: bcae21eb67e772ac

clusterSecretStores:
  gcpsm:
    provider:
      fake:
        data:
        - key: /gitlab/registry
          valueMap:
            url: https://registry.example.com
            email: devops@example.com
            username: kubernetes
            password: 89c12fc1ef680457
            auth: a3ViZXJuZXRlczo4OWMxMmZjMWVmNjgwNDU3
