image:
  repository: traefik/whoami
  tag: v1.8.7

deployments:
  web:
    imagePullSecrets:
    - name: registry
    containers:
      web:
        envFromSecret:
          postgresql:
            DB_PASSWORD: password

externalSecrets:
  postgresql:
    refreshInterval: "0"
    secretStoreRef:
      name: vault
    data:
    - secretKey: password
      remoteRef:
        key: /postgresql/whoami/password

secretStores:
  vault:
    refreshInterval: 86400  # seconds
    provider:
      fake:
        data:
        - key: /postgresql/whoami/password
          value: bcae21eb67e772ac

clusterExternalSecrets:
  registry:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: '{{ $.Release.Namespace }}'
    externalSecretSpec:
      refreshInterval: 4h
      secretStoreRef:
        kind: ClusterSecretStore
        name: gcpsm
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "{{ .url }}": {
                  "auth": "{{ .auth }}",
                  "email": "{{ .email }}",
                  "username": "{{ .username }}",
                  "password": "{{ .password }}"
                }
              }
            }
      dataFrom:
      - extract:
          key: /gitlab/registry

clusterSecretStores:
  gcpsm:
    provider:
      fake:
        data:
        - key: /gitlab/registry
          valueMap:
            url: https://registry.example.com
            email: devops@example.com
            username: kubernetes
            password: 89c12fc1ef680457
            auth: a3ViZXJuZXRlczo4OWMxMmZjMWVmNjgwNDU3
