image:
  repository: traefik/whoami
  tag: v1.8.7

deployments:
  api:
    containers:
      api: {}

services:
  api:
    type: NodePort
    ports:
    - port: 80

ingresses:
  api:
    annotations:
      networking.gke.io/v1beta1.FrontendConfig: '{{ $.Release.Name }}-api'
    defaultBackend:
      serviceName: api
      servicePort: 80

gcp:
  frontendConfigs:
    api:
      sslPolicy: gke-ingress-ssl-policy
      redirectToHttps:
        enabled: true
