x-api-domain-name: &api_domain_name api.example.com
x-ui-domain-name: &ui_domain_name www.example.com

image:
  repository: traefik/whoami
  tag: v1.8.7

deployments:
  api:
    containers:
      api: {}
  admin:
    containers:
      admin: {}

services:
  api:
    type: NodePort
    ports:
    - port: 80
  admin:
    ports:
    - port: 3000

ingresses:
  api:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: *api_domain_name
    defaultBackend:
      serviceName: api
      servicePort: 80
    tls:
      hosts: [*api_domain_name]
  ui:
    rules:
    - host: *ui_domain_name
      paths:
      - path: /
        pathType: Prefix
        serviceName: api
        servicePort: 80
      - path: /admin
        pathType: Prefix
        serviceName: admin
        servicePort: 3000
