image:
  repository: traefik/whoami
  tag: v1.8.7

deployments:
  web:
    serviceAccountName: web
    containers:
      web: {}

rbac:
  serviceAccounts:
    web: {}
  roles:
    web:
      rules:
      - apiGroups: [""]
        resources: ["pods"]
        verbs: ["get", "watch", "list"]
  roleBindings:
    web:
      roleName: web
      serviceAccounts:
      - web
