image:
  repository: traefik/whoami
  tag: v1.8.7

deployments:
  web:
    containers:
      web: {}
  worker:
    containers:
      worker: {}

services:
  web:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
  worker:
    ports:
    - port: 8793
