name: Lint and Test charts

on:
  pull_request:
    paths:
    - 'charts/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup chart-testing
      uses: helm/chart-testing-action@v2.3.1

    - name: Lint
      run: ct lint --target-branch ${{ github.base_ref }}

    - name: Create kind cluster
      uses: helm/kind-action@v1.5.0
      with:
        node_image: kindest/node:v1.22.15

    - name: Test
      run: ct install --target-branch ${{ github.base_ref }}
